### ISSUE TITLE
Use https://github.com/wuub/rxv ?

### ISSUE THREAD

**Issue by blysik** [IndigoDomotics/indigo-yamaharx#7]
https://github.com/wuub/rxv looks like a well maintained python library for dealing with Yamaha devices.  Would it make sense to use that underneath the hood of this plugin?

**Comment by discgolfer1138** [comment]
I haven't had much experience implementing 3rd party libs in Indigo plugins as it most of the ones I've build have only consisted of simple calls to restful apis.   Feel free to open a PR if you'd like :)

**Comment by indigodomo** [comment]
The 1.0.0 version of the plugin uses a custom (and embedded) version of the rxv library to add support for the RX-Vx73 receiver line.
